CREATE DATABASE IF NOT EXISTS rtr;

USE rtr;

CREATE TABLE IF NOT EXISTS photos (
  id INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
  picOne VARCHAR(75) DEFAULT NULL,
  picTwo VARCHAR(75) DEFAULT NULL,
  picThree VARCHAR(75) DEFAULT NULL,
  picFour VARCHAR(75) DEFAULT NULL )
  AUTO_INCREMENT = 100;
